import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { Sidebar } from './sidebar/sidebar'
import clsx from 'clsx'
import '../styles/globals.css'

const openSans = Open_Sans({
    weight: ['300', '400', '500', '700', '800'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={clsx(openSans.className, 'flex w-full h-full')}>
                <nav className="kzen-side-bar">
                    <Sidebar />
                </nav>
                <main className="kzen-main">{children}</main>
            </body>
        </html>
    )
}
